sudo: false
language: "python"
python:
  - "3.4"
  - "3.5"
install:
  - "pip3 install -U pip"  # upgrade pip
  - "pip3 install coveralls"  # for test coverage
  - "git clone https://github.com/sirfoga/pyhal.git"  # clone repo
  - "cd pyhal"
  - "pip3 install ."  # run local setup
script:
  - "coverage"
notifications:
  email: "false"  # no email notifications
