language: "python"
python:
  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.5-dev"
install:
  - "pip install -U pip"  # upgrade pip
  - "pip install coveralls"
  - "pip install git+https://github.com/sirfoga/hal.git"
script:
  - "coverage"
after_success:
  - "coverage run --source=hal setup.py test"
  - "coveralls"
notifications:
  email: "false"  # no email notifications
