sudo: false
language: "python"
python:
  - "3.5"
install:
  - "pip3 install -U pip"  # upgrade pip
  - "pip3 install codecov"  # test coverage
  - "pip3 install pylint pylint-exit"  # measure code lint
  - "git clone --depth=1 https://github.com/sirfoga/pyhal.git"  # clone repo
  - "cd pyhal"
  - "pip3 install ."  # run local setup
script:
  - "codecov"  # test coverage
  - "pylint3 -j 8 hal/* || pylint-exit $?"  # measure code lint
notifications:
  email: "false"  # no email notify
