sudo: false
language: "python"
python:
  - "3.5"
install:
  - "pip3 install -U pip"  # upgrade pip
  - "pip3 install codecov"  # for test coverage
  - "git clone --depth=1 https://github.com/sirfoga/pyhal.git"  # clone repo
  - "cd pyhal"
  - "pip3 install ."  # run local setup
script:
  - "codecov"
notifications:
  email: "false"  # no email notify
