language: python  # language used in repo
python:  # versions used
  - "3.4"
#addons:
#  apt:
#    packages:
#       - python3-numpy  # matplotlib
#       - python3-matplotlib
#       - libpng-dev
#       - libfreetype6-dev
#       - python3-scipy  # scipy
#       - python3-pandas
#       - python3-nose
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
install: "pip3 install ."  # command to install dependencies
after_success:
    - coveralls
notifications:
  email: false  # no email notifications
# script: pytest  # command to run tests
