language: python  # language used in repo
python:  # versions used
  - "3.2"
#addons:
#  apt:
#    packages:
#       - python3-numpy  # matplotlib
#       - python3-matplotlib
#       - libpng-dev
#       - libfreetype6-dev
#       - python3-scipy  # scipy
#       - python3-pandas
#       - python3-nose
install: "pip3 install mutagen"  # command to install dependencies
notifications:
  email: false  # no email notifications
# script: pytest  # command to run tests
