language: "python"  # language used in repo
python:  # versions used
#  - "3.2"
  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.5-dev"
#os:
#  - linux
#  - windows
#  - macosx
addons:
  apt:
    packages:
#       - python3-numpy  # matplotlib
#       - python3-matplotlib
#       - libpng-dev
#       - libfreetype6-dev
#       - python3-scipy  # scipy
#       - python3-pandas
#       - python3-nose
before_install:
#  - "pip install pytest pytest-cov"
#  - "pip install coveralls"

install:
  - "pip install -U pip"
  - "pip install python-coveralls"
  - "pip install install git+https://github.com/sirfoga/hal.git"
script:
  - "coverage"
after_success:
  - "coveralls"
notifications:
  email: "false"  # no email notifications
