docs_dir: _build/pydocmd
pages:
- {Home: index.md}
- 'hal.charts: Charts':
  - {Bar charts: charts/bars.md}
  - {Correlation charts: charts/correlation.md}
  - {Models: charts/models.md}
  - {Plotters: charts/plotter.md}
- 'hal.cvs: Concurrent Versions System':
  - {Git tools: cvs/gits.md}
  - {Versioning: cvs/versioning.md}
- 'hal.data: Data structures':
  - {Dicts: data/dicts.md}
  - {Linked List: data/linked_list.md}
  - {Lists: data/lists.md}
  - {Matrix: data/matrix.md}
- 'hal.files: Deal with file systems':
  - {Parsers: files/parsers.md}
repo_url: https://github.com/sirfoga/pyhal
site_dir: _build/site
site_name: PyHal documentation
theme: readthedocs
